### ISSUE TITLE
Unable to extract speaker name when language is russian

### ISSUE THREAD

**Issue by pixelastic** [algolia/talksearch-scraper#52]
When trying to index the OdessaJS conference, the Google NLP API chokes with the following error:

```
{ Error: 3 INVALID_ARGUMENT: The language ru is not supported for entity analysis.
    at Object.exports.createStatusError (/home/tim/local/www/algolia/talksearch/talksearch-scraper/node_modules/grpc/src/common.js:87:15)
    at Object.onReceiveStatus (/home/tim/local/www/algolia/talksearch/talksearch-scraper/node_modules/grpc/src/client_interceptors.js:1188:28)
    at InterceptingListener._callNext (/home/tim/local/www/algolia/talksearch/talksearch-scraper/node_modules/grpc/src/client_interceptors.js:564:42)
    at InterceptingListener.onReceiveStatus (/home/tim/local/www/algolia/talksearch/talksearch-scraper/node_modules/grpc/src/client_interceptors.js:614:8)
    at callback (/home/tim/local/www/algolia/talksearch/talksearch-scraper/node_modules/grpc/src/client_interceptors.js:841:24)
  code: 3,
  metadata: Metadata { _internal_repr: {} },
  details: 'The language ru is not supported for entity analysis.',
  note: 'Exception occurred in retry method that was not classified as transient' }
```

We might want to either:
- handle this gracefully by skipping it
- have a whitelist of language that can have NLP

**Comment by pixelastic** [comment]
Fixed in `develop`. We gracefully handle it, displaying a warning about the issue but moving on.
